services:
  hermes:
    build:
      context: .
      args:
        # Passes the variables from the host/env to the Docker build process
        - UID=${UID}
        - GID=${GID}
    container_name: hermes
    restart: unless-stopped
    command: sh -c "uv sync && HERMES_ALLOW_ROOT_GATEWAY=1 uv run hermes gateway run"
    ports:
      - "8642:8642"
      - "9119:9119"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./opt_data:/opt/data
      - ./opt_hermes/.hermes:/opt/hermes/.hermes
      - ./output:/output
      # Mount the socket so the container can talk to the host's Docker engine
      - /var/run/docker.sock:/var/run/docker.sock      
      
    environment:
      # Passes the variables to the running container
      - HERMES_UID=${UID}
      - HERMES_GID=${GID}      
      - GATEWAY_ALLOW_ALL_USERS=true
      - HERMES_OUTPUT_PATH=${PWD}/output
      - HERMES_DASHBOARD=1          
      - npm_config_cache=/tmp/.npm      
      - UV_CACHE_DIR=/opt/data/.uv-cache
      - HOME=/opt/hermes
      - XDG_CACHE_HOME=/tmp/.cache